blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/AlexeyShalaev/hse-doc-studio/discussions
    about: Ask a question or start a discussion about hse-doc-studio
