from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol
from uuid import UUID

from hse_doc_studio.core.catalog import PackInfo, TemplateVersion
from hse_doc_studio.core.entities import (
    AgentPersona,
    AgentRunRecord,
    AIProvider,
    ChangeLogEntry,
    ChatMessage,
    ChatSession,
    ChatSummaryBlock,
    CompileRecord,
    PackSubmissionRecord,
    Project,
    SigningIdentity,
)
from hse_doc_studio.core.value_objects import FormState, SignaturesState


@dataclass(frozen=True)
class BrowseEntry:
    name: str
    path: Path
    is_dir: bool
    is_hidden: bool


class IProjectRepository(Protocol):
    def get(self, folder: Path) -> Project | None: ...
    def save(self, project: Project) -> None: ...


class IProjectIndexRepository(Protocol):
    def list_known(self) -> list[Path]: ...
    def register(self, folder: Path) -> None: ...
    def unregister(self, folder: Path) -> None: ...


class ICompileRepository(Protocol):
    def get(self, compile_id: UUID) -> CompileRecord | None: ...
    def list_for_document(self, project_folder: Path, doc_id: str) -> list[CompileRecord]: ...
    def save(self, record: CompileRecord) -> None: ...


class ITemplateRepository(Protocol):
    def list_packs(self) -> list[PackInfo]: ...
    def get_version(self, pack_id: str, template_id: str, version: str) -> TemplateVersion | None: ...
    def list_versions(self, pack_id: str, template_id: str) -> list[str]: ...
    def version_dir(self, pack_id: str, template_id: str, version: str) -> Path | None: ...


class ISignatureRepository(Protocol):
    def get_state(self, project_folder: Path) -> SignaturesState: ...
    def save_state(self, project_folder: Path, state: SignaturesState) -> None: ...


class IFormStateRepository(Protocol):
    # Per-form raw answers, stored at <folder>/.hse-studio/forms/<form_id>.json.
    # The repo is form-agnostic: it round-trips a FormState blob and knows
    # nothing about which fields a given form declares.
    def get_state(self, project_folder: Path, form_id: str) -> FormState | None: ...
    def save_state(self, project_folder: Path, form_id: str, state: FormState) -> None: ...


class IChangeLogRepository(Protocol):
    def list(self, project_folder: Path, doc_id: str | None = None) -> list[ChangeLogEntry]: ...
    def append(self, project_folder: Path, entry: ChangeLogEntry) -> None: ...


class IPackSubmissionRepository(Protocol):
    def list_for_project(self, project_folder: Path) -> list[PackSubmissionRecord]: ...
    def get(self, project_folder: Path, submission_id: UUID) -> PackSubmissionRecord | None: ...
    def save(self, record: PackSubmissionRecord) -> None: ...


@dataclass(frozen=True)
class ScannedEntry:
    """Запись обхода дерева проекта: путь плюс уже снятая статистика.

    Статистика едет вместе с путём намеренно: она и так читается при листинге
    каталога, а повторный `stat()` на каждый элемент — лишний системный вызов,
    и на бинд-маунте Docker это заметно.
    """

    path: str
    is_dir: bool
    size: int
    mtime: float


class IFileRepository(Protocol):
    def read(self, folder: Path, path: str) -> bytes: ...
    def write(self, folder: Path, path: str, content: bytes) -> None: ...
    def scan(self, folder: Path) -> list[ScannedEntry]: ...
    def list_files(self, folder: Path) -> list[str]: ...
    def list_dirs(self, folder: Path) -> list[str]: ...
    def exists(self, folder: Path, path: str) -> bool: ...
    def delete(self, folder: Path, path: str) -> None: ...
    def move(self, folder: Path, src: str, dst: str) -> None: ...
    def mkdir(self, folder: Path, path: str) -> None: ...


class ISettingsRepository(Protocol):
    def get(self) -> dict[str, Any]: ...
    def save(self, settings: dict[str, Any]) -> None: ...


class IAIProviderRepository(Protocol):
    # CRUD over the local list of configured AI providers. The use case owns id
    # / created_at generation and the "keep the existing key when blank" rule;
    # the repository is a dumb persistence layer (mirrors IProjectRepository).
    def list_all(self) -> list[AIProvider]: ...
    def get(self, provider_id: UUID) -> AIProvider | None: ...
    def create(self, provider: AIProvider) -> None: ...
    def update(self, provider: AIProvider) -> None: ...
    def delete(self, provider_id: UUID) -> bool: ...


class ISigningIdentityRepository(Protocol):
    # CRUD over locally-stored signing credentials (data_dir/signing_identities.json).
    # Key material lives separately in data_dir/signing_keys/<id>/; the repo only
    # manages the metadata records. Mirrors IAIProviderRepository.
    def list_all(self) -> list[SigningIdentity]: ...
    def get(self, identity_id: UUID) -> SigningIdentity | None: ...
    def create(self, identity: SigningIdentity) -> None: ...
    def delete(self, identity_id: UUID) -> bool: ...
    # Key-material helpers — the repo owns the on-disk layout.
    def key_dir(self, identity_id: UUID) -> Path: ...


class IAgentPersonaRepository(Protocol):
    # CRUD over user-defined agent roles (data_dir/agent_personas.json). Dumb
    # persistence layer (mirrors IAIProviderRepository); the use case owns id /
    # created_at generation and validation.
    def list_all(self) -> list[AgentPersona]: ...
    def get(self, persona_id: UUID) -> AgentPersona | None: ...
    def create(self, persona: AgentPersona) -> None: ...
    def update(self, persona: AgentPersona) -> None: ...
    def delete(self, persona_id: UUID) -> bool: ...


class IFilesystemBrowser(Protocol):
    def browse(self, path: Path) -> tuple[Path | None, list[BrowseEntry]]: ...


class IChatRepository(Protocol):
    # Folder-scoped persistence of agent chat sessions, their transcripts, the
    # rolling compaction summaries, and per-turn run records. Mirrors the other
    # per-project repos (e.g. IPackSubmissionRepository): getters take the
    # project folder; the use case resolves project_id → folder. The transcript
    # is append-only (see the JSON impl) so `append_message` assigns and returns
    # the monotonic seq.

    # sessions
    def list_sessions(self, project_folder: Path) -> list[ChatSession]: ...
    def get_session(self, project_folder: Path, session_id: UUID) -> ChatSession | None: ...
    def save_session(self, session: ChatSession) -> None: ...
    def delete_session(self, project_folder: Path, session_id: UUID) -> bool: ...

    # messages (append-only transcript). project_folder is passed explicitly
    # because a ChatMessage carries only session_id, not its on-disk location.
    def append_message(self, project_folder: Path, message: ChatMessage) -> int: ...  # returns assigned seq
    def list_messages(self, project_folder: Path, session_id: UUID) -> list[ChatMessage]: ...
    def update_message(self, project_folder: Path, message: ChatMessage) -> None: ...  # rare: compaction flag only
    # Mark messages with seq <= through_seq as compacted (covered by a summary) in
    # one transcript rewrite; the raw text is kept, only excluded from replay.
    def mark_compacted(self, project_folder: Path, session_id: UUID, through_seq: int) -> int: ...

    # rolling compaction summaries
    def list_summaries(self, project_folder: Path, session_id: UUID) -> list[ChatSummaryBlock]: ...
    def append_summary(self, project_folder: Path, summary: ChatSummaryBlock) -> None: ...

    # background-turn run records
    def get_run(self, project_folder: Path, run_id: UUID) -> AgentRunRecord | None: ...
    def list_runs(self, project_folder: Path, session_id: UUID) -> list[AgentRunRecord]: ...
    def save_run(self, record: AgentRunRecord) -> None: ...
    def list_all_run_ids(self, project_folder: Path) -> list[UUID]: ...  # recovery scan
